version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    expose:
      - 4000
    environment:
      - PORT=4000
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    expose:
      - 80

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
